### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by SkyWa7ch3r** [EoRImaging/PyFHD#33]
# Roadmap to 1.0

This issue will outline the steps needed to get to the first release, the goal is to do this release at the end of the year (2023). Upon release of 1.0 PyFHD will be given to the EoR community in full.

## Calibration
- [X] Translate Calibration
- [X] Test Calibration
- [x] Get the Calibration code to run on real data as part of the Python pipeline
- [x] Merge the PR once approved

## Gridding
- [x] Make the gridding code fully compatible with the full Python pipeline
- [x] Work out a solution to import the beam in that doesn't require a HPC to run PyFHD
- [x] Get the Calibration and gridding code to work together
- [x] Merge the PR once approved

## Obs
- [x] Add one or two tests for the obs function, recent testing has made it clear it needs a test or two 

## `vis_flag_basic`
- [x] Translate `vis_flag_basic`
- [x] Test `vis_flag_basic`
- [x] Integrate it into Python pipeline

## `vis_flag`
- [x] vis_flag needs to pass its tests

## `vis_weights_update`
- [x] `vis_weights_update` needs to pass its tests

## `fhd_quickview`
- [x] Translate `fhd_quickview` (Some parts won't be translated)
- [x] Test `fhd_quickview`
- [x] Integrate it into the Python pipeline

## `healpix_snapshot_cube_generate`
- [x] Translate `healpix_snapshot_cube_generate`
- [x] Test `healpix_snapshot_cube_generate`
- [x] Integrate it into the Python pipeline

## Testing other Telescopes
- [x] Integrate `pyuvdata` beam or `beam_fits` to enable the creation of the necessary parts of the `psf` dictionary that `PyFHD` requires to complete gridding and HEALPIX calculations. 
- [ ] Test with HERA Data
- [ ] Test with LWA Data
- [ ] Test more recent MWA data (Phase II)

## Virtual Community Q & A, Tutorial and Documentation
- [x] Find the best day and time for the EoR community to do a Q & A @SkyWa7ch3r @nicholebarry 
- [x] Contact members of the EoR community for help on documentation @nicholebarry 
- [x] Develop the Contribution guide before the event and use that to create a talk for the community on helpful development advice for using PyFHD @SkyWa7ch3r 
- [x] Work out an agenda for the session @SkyWa7ch3r @nicholebarry 

## I/O
- [x] Add save points and checkpoints for every part of the Python Pipeline
- [x] Add load points for each part as a part of the checkpoints
- [x] Make a save and load function that isn't `deepdish` as `deepdish` is no longer supported :(

## Configuration
- [x] Clean up the configuration options to remove unused options or duplicate options
- [x] Ensure that `pyfhd.yaml` has comments for configuration and has 'good' defaults
- [x] Ensure all arguments are in their correct group
- [x] Remove Hardcoded variables as much as possible
- [x] Deal with deprecation of setup.py and use `pyproject.toml` instead

## Code Cleanup and Refactoring
- [x] Ensure all functions are in their most appropriate modules given their use throughout PyFHD
- [x] Removed any unused functions even if they have been translated, mention any translated but removed code in the changelog in case someone wants to use it later
- [x] Switch to using the black formatter and format across project with a pre-commit available

## Documentation
- [x] Fill in all remaining docstrings for the API documentation
- [x] Ensure Typing is consistently used across PyFHD with proper use of the typing module and NumPy typing module
- [x] Add examples of running just PyFHD code same as the IDL examples that exist in the docs now
    - [x] Add tutorial for adding options to PyFHD into the contribution guide
    - [x] Add tutorial for PyFHD testing and creating tests for PyFHD
    - [X] Add information on the input & output of PyFHD
    - [X] Adjust the tutorial given for calibration from Jack
    - [X] Engage EoR community for more tutorials
    - [x] Adjust contribution guide to install and use [uv](https://docs.astral.sh/uv/)
- [x] Add a contribution guide for developers of PyFHD (include PyFHD & FHD installation instructions)
- [x] Add a contribution guide for new translation endeavours
- [x] Adjust contribution guide to add guides for making tests
- [x] Adjust contribution guide to add docs on making docs
- [x] Adjust contribution guide for doing formatting
- [X] Pull Request Template
- [X] Implement Changelog
- [ ] Add v1.0 notes to the changelog
- [x] Update the installation page for Python only

## Testing
- [ ] Add a testing badge for pytest and code coverage from pytest
- [x] Add HTML reports to the sphinx documentation
- [ ] Github action for pytest
- [ ] Work with the EoR community to store the current tests
- [ ] Work with the EoR community to create CI for existing tests
- [ ] Test the pipeline on real data and ensure it can do actual science!

## PyPI & DockerHub
- [x] Publish to [PyPI](https://packaging.python.org/en/latest/tutorials/packaging-projects/)
- [ ] GitHub Action fr PyPi
- [ ] Action or Hook for Zenodo
- [x] Publish to DockerHub via GitHub Actions

## JOSS
- [ ] Submit PyFHD to [JOSS](https://joss.theoj.org/)
- [ ] Create a Guide for referencing the package when used for publishing papers and results generated by PyFHD

## ADACS
- [ ] Update FHD description on ADACS Website
